stages:
  - build
  - test
  - release

variables:
  BUILD_DIR: "build"
  VS_DEV_CMD: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

build:
  stage: build
  tags:
    - windows
  script:
    - call "%VS_DEV_CMD%"
    - mkdir %BUILD_DIR%
    - cd %BUILD_DIR%
    - cmake .. -G "Visual Studio 17 2022" -A x64
    - cmake --build . --config Release

test:
  stage: test
  tags:
    - windows
  script:
    - call "%VS_DEV_CMD%"
    - cd %BUILD_DIR%
    - ctest -C Release --output-on-failure

release:
  stage: release
  tags:
    - windows
  script:
    - echo "Creating release..."
    - mkdir release
    - copy %BUILD_DIR%\Release\your_executable.exe release\
    - echo "Release files ready."
  artifacts:
    paths:
      - release/
    expire_in: 7 days
