stages:
  - build
  - test
  - release

variables:
  BUILD_DIR: "build"
  VS_DEV_CMD: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
  PROJECT_DIR: "C:\\C++projects\\SlimV-Fracod"  # Your project directory
  SOLUTION_FILE: "SlimV-Fracod.sln"
  RELEASE_DIR: "x64\\Release"
  EXE_NAME: "your_executable.exe"  # Replace with the name of your executable

build:
  stage: build
  tags:
    - windows
  script:
    - call "%VS_DEV_CMD%"  # Set up the Visual Studio environment
    - cd %PROJECT_DIR%      # Change to the project directory
    - MSBuild "%SOLUTION_FILE%" /p:Configuration=Release /p:Platform=x64  # Build the solution using MSBuild

test:
  stage: test
  tags:
    - windows
  script:
    - call "%VS_DEV_CMD%"  # Set up the Visual Studio environment
    - cd %PROJECT_DIR%\%BUILD_DIR%\%RELEASE_DIR%  # Change to the build directory
    - echo "Running tests..."  # Insert your test commands here (e.g., using a test framework like Google Test or MSTest)

release:
  stage: release
  tags:
    - windows
  script:
    - echo "Creating release..."
    - mkdir release  # Create release directory
    - copy %PROJECT_DIR%\%BUILD_DIR%\%RELEASE_DIR%\%EXE_NAME% release\  # Copy the executable to release folder
    - echo "Release files ready."
  artifacts:
    paths:
      - release/  # Store release directory as artifact
