stages:
  - build
  - test
  - release

variables:
  VS_DEV_CMD: "C:\\Programme\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
  PROJECT_DIR: "C:\\C++projects\\SlimV-Fracod"
  SOLUTION_FILE: "SlimV-Fracod.sln"
  RELEASE_DIR: "x64\\Release"
  EXE_NAME: "SlimV-Fracod.exe"

build:
  stage: build
  tags:
    - windows
  script:
    - echo "Initializing MSVC environment..."
    - cmd /c "%VS_DEV_CMD%"
    - cd "%PROJECT_DIR%"
    - echo "Building solution..."
    - MSBuild "%SOLUTION_FILE%" /p:Configuration=Release /p:Platform=x64
  artifacts:
    paths:
      - $RELEASE_DIR\$EXE_NAME
    expire_in: 1 week
  only:
    - branches
    - tags

test:
  stage: test
  tags:
    - windows
  script:
    - echo "Skipping actual tests for now (no tests defined)"
  allow_failure: true
  only:
    - branches
    - tags

release:
  stage: release
  tags:
    - windows
  script:
    - echo "Packaging release..."
    - mkdir release
    - copy "%PROJECT_DIR%\\%RELEASE_DIR%\\%EXE_NAME%" release\
    - echo "Release packaged."
  artifacts:
    paths:
      - release/
    expire_in: 1 week
  only:
    - tags
