stages:
  - build
  - test
  - release

variables:
  BUILD_DIR: "build"
  VS_DEV_CMD: "C:\\Programme\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
  PROJECT_DIR: "C:\\C++projects\\SlimV-Fracod"  # Your project directory
  SOLUTION_FILE: "SlimV-Fracod.sln"
  RELEASE_DIR: "x64\\Release"
  EXE_NAME: "SlimV-Fracod.exe"  # Replace with the name of your executable

build:
  stage: build
  tags:
    - windows
  script:
    - echo "Initializing MSVC environment..."
    - cmd /c '"C:\\Programme\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat" && cd %PROJECT_DIR% && msbuild "%SOLUTION_FILE%" /p:Configuration=Release /p:Platform=x64'


sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

release:
  stage: release
  tags:
    - windows
  script:
    - echo "Creating release..."
    - cmd /c "echo %PROJECT_DIR%\%RELEASE_DIR%\%EXE_NAME%"
    - cmd /c "dir %PROJECT_DIR%\%RELEASE_DIR%"
    #- cmd /c "mkdir release && copy %PROJECT_DIR%\%RELEASE_DIR%\%EXE_NAME% release\\"
    - cmd /c "mkdir release && copy C:\C++projects\SlimV-Fracod\x64\Release\SlimV-Fracod.exe release"

  artifacts:
    paths:
      - release/  # Store release directory as artifact
